fos_user_security:
    resource: @FOSUserBundle/Resources/config/routing/security.xml
vespolina_admin:
    resource: @VespolinaAdminBundle/Resources/config/routing/admin.xml
    prefix:   /admin/
vespolina_commerce_checkout:
    resource: "@VespolinaCommerceBundle/Resources/config/routing/checkout.xml"
    prefix:   /
vespolina_commerce_cart:
    resource: "@VespolinaCommerceBundle/Resources/config/routing/cart.xml"
    prefix:   /
vespolina_commerce_product:
    resource: "@VespolinaCommerceBundle/Resources/config/routing/product.xml"
    prefix:   /
vespolina_taxonomy:
    resource: "@VespolinaCommerceBundle/Resources/config/routing/taxonomy.xml"
    prefix:   /
vespolina_store:
    resource: "@VespolinaStoreBundle/Resources/config/routing/store.xml"
    prefix:   /