vespolina_cart:
    db_driver: mongodb
vespolina_pricing:
    db_driver: mongodb
vespolina_product:
    db_driver: mongodb
    product_manager:
#        primary_identifier: sku
        identifiers:
            sku: Vespolina\ProductBundle\Document\SKUIdentifier
    product:
        form:
            type:               Application\Vespolina\ProductBundle\Form\Type\ProductFormExtendedType #vespolina.product.form.type
#            handler_service:    vespolina.product.form.handler
#            name:               vespolina_product_form
vespolina_monetary:
    currency:
        base_currency:  EUR